version: "3.7"
services:
  app:
    build:
      args:
        user: procode
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laravel-blog
    container_name: laravel-blog
    restart: unless-stopped
    working_dir: /var/www/html/
    volumes:
      - ./:/var/www/html/
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: laravel-blog-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: laravel-blog-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html/
      - ./nginx:/etc/nginx/conf.d/
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
